# Generated by Django 4.2.1 on 2023-06-08 18:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=2000)),
                ('last_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.TextField()),
                ('confirmation_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('language', models.CharField(blank=True, choices=[('uz', 'Uz'), ('en', 'En'), ('ru', 'Ru')], max_length=5, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.TextField()),
                ('two_step_verification_password', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('custom', 'Custom')], default='free', max_length=1000)),
                ('upload_projects', models.PositiveBigIntegerField(default=5, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(1000)])),
                ('write_blog', models.PositiveBigIntegerField(default=3, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(1000)])),
                ('join_team', models.PositiveBigIntegerField(default=2, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(1000)])),
                ('get_badges', models.PositiveBigIntegerField(default=3, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(1000)])),
                ('themes', models.PositiveBigIntegerField(default=2, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(1000)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'subscription_plans',
            },
        ),
    ]
