# Generated by Django 4.2 on 2023-06-15 03:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='VideoLessonsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('caption', models.TextField(max_length=1024)),
                ('video', models.TextField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('course_cost', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000001)])),
                ('discount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoLessonsRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.videolessonsmodel')),
            ],
        ),
    ]
