# Generated by Django 4.2 on 2023-06-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_messages_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='seen_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
