# Generated by Django 4.2.6 on 2023-11-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatGPT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("subject", models.TextField()),
                ("content", models.TextField()),
                ("role", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ("id",),
                "abstract": False,
            },
        ),
    ]
