# Generated by Django 4.2 on 2023-08-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_wallet_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('customer', 'Customer'), ('company_representative', 'Company representative')], default='developer', max_length=100),
            preserve_default=False,
        ),
    ]
