# Generated by Django 4.2 on 2023-08-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invited_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
