# Generated by Django 4.2.3 on 2023-09-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_service_remove_pinnedchat_chat_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userservice",
            name="expires_in",
            field=models.DateTimeField(null=True),
        ),
    ]
