# Generated by Django 4.2 on 2023-08-16 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S3Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True)),
                ('bucket', models.CharField(max_length=500)),
                ('key', models.CharField(max_length=300, unique=True)),
                ('file_id', models.UUIDField(default=uuid.uuid5, editable=False, unique=True)),
            ],
            options={
                'db_table': 's3_attachments',
            },
        ),
    ]
