# Generated by Django 4.2.6 on 2023-11-05 08:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="S3Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("url", models.TextField(blank=True, null=True)),
                ("bucket", models.CharField(max_length=500)),
                ("key", models.CharField(max_length=300, unique=True)),
                (
                    "file_id",
                    models.UUIDField(default=uuid.uuid5, editable=False, unique=True),
                ),
            ],
            options={
                "db_table": "s3_attachments",
            },
        ),
        migrations.CreateModel(
            name="TelegramStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("chat_id", models.BigIntegerField()),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("file", "File"),
                            ("document", "Document"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file_id", models.TextField()),
                ("file_unique_id", models.TextField()),
                ("file_size", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                ("performer", models.CharField(blank=True, max_length=500, null=True)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("file_name", models.CharField(blank=True, max_length=500, null=True)),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "thumbnail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thumbnails",
                        to="core.telegramstorage",
                    ),
                ),
            ],
            options={
                "db_table": "telegram_storage",
            },
        ),
    ]
