# Generated by Django 4.2.3 on 2023-09-03 12:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="s3attachment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="s3attachment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s3attachment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="TelegramStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("chat_id", models.BigIntegerField()),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("file", "File"),
                            ("document", "Document"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file_id", models.TextField()),
                ("file_unique_id", models.TextField()),
                ("file_size", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                ("performer", models.CharField(blank=True, max_length=500, null=True)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("file_name", models.CharField(blank=True, max_length=500, null=True)),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "thumbnail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thumbnails",
                        to="core.telegramstorage",
                    ),
                ),
            ],
            options={
                "db_table": "telegram_storage",
            },
        ),
    ]
