# Generated by Django 4.2.3 on 2023-09-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_s3attachment_created_at_s3attachment_deleted_at_and_more"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.telegramstorage",
            ),
        ),
    ]
