# Generated by Django 4.2.5 on 2023-10-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_subscription_id", models.CharField(max_length=250)),
                ("current_period_end", models.DateTimeField()),
            ],
            options={
                "db_table": "payments_subscriptions",
            },
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
