# Generated by Django 4.2.1 on 2023-06-08 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company_logoes/')),
                ('field', models.CharField(choices=[('it', 'Information Technologies'), ('ecommerce', 'E-Commerce'), ('marketing_sales', 'Marketing & Sales')], max_length=500)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.BigIntegerField(blank=True, null=True)),
                ('longitude', models.BigIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=500)),
                ('info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('ceo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_started_at', models.DateTimeField()),
                ('work_ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('company', models.ManyToManyField(to='company.company')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
