# Generated by Django 4.2.1 on 2023-09-24 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "__first__"),
        ("mediafiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="videoranking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="videoranking",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mediafiles.video"
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="banner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="banners",
                to="core.s3attachment",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="mediafiles.category",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="videos",
                to="core.s3attachment",
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.s3attachment"
            ),
        ),
    ]
