# Generated by Django 4.2.3 on 2023-09-03 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("mediafiles", "0002_videoranking"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="videoranking",
            options={"ordering": ("id",)},
        ),
        migrations.AddField(
            model_name="image",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name="category",
            table="categories",
        ),
    ]
