# Generated by Django 4.2.1 on 2023-06-16 12:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_company_update_at_employee_update_at_and_more'),
        ('mediafiles', '0002_badge'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=300)),
                ('priority', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('logo', models.ImageField(upload_to='badges/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deleted_badges',
            },
        ),
        migrations.CreateModel(
            name='DeletedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('object_id', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deleted_images',
            },
        ),
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=2000)),
                ('last_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.TextField()),
                ('confirmation_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('language', models.CharField(blank=True, choices=[('uz', 'Uz'), ('en', 'En'), ('ru', 'Ru')], max_length=5, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.TextField()),
                ('two_step_verification_password', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deleted_users',
            },
        ),
        migrations.CreateModel(
            name='DeletedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.TextField()),
                ('object_id', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deleted_videos',
            },
        ),
        migrations.CreateModel(
            name='DeletedUserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediafiles.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'deleted_user_badges',
            },
        ),
        migrations.CreateModel(
            name='DeletedTeamBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediafiles.badge')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.team')),
            ],
            options={
                'db_table': 'deleted_team_badges',
            },
        ),
        migrations.CreateModel(
            name='DeletedTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'deleted_teams',
            },
        ),
        migrations.CreateModel(
            name='DeletedSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('custom', 'Custom')], default='free', max_length=1000)),
                ('upload_projects', models.PositiveBigIntegerField(default=5, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(1000)])),
                ('write_blog', models.PositiveBigIntegerField(default=3, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(1000)])),
                ('join_team', models.PositiveBigIntegerField(default=2, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(1000)])),
                ('get_badges', models.PositiveBigIntegerField(default=3, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(1000)])),
                ('themes', models.PositiveBigIntegerField(default=2, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(1000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'deleted_subscription_plans',
            },
        ),
        migrations.CreateModel(
            name='DeletedSavedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'deleted_saved_projects',
            },
        ),
        migrations.CreateModel(
            name='DeletedRankingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'deleted_ranking_projects',
            },
        ),
        migrations.CreateModel(
            name='DeletedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'deleted_projects',
            },
        ),
        migrations.CreateModel(
            name='DeletedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('parse_mode', models.CharField(blank=True, choices=[('html', 'HTML'), ('markdown', 'MARKDOWN'), ('cybersell', 'CYBERSELL')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': 'deleted_posts',
            },
        ),
        migrations.CreateModel(
            name='DeletedMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'deleted_members',
            },
        ),
        migrations.CreateModel(
            name='DeletedEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_started_at', models.DateTimeField()),
                ('work_ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company', models.ManyToManyField(to='company.company')),
                ('user', models.ManyToManyField(to='users.user')),
            ],
            options={
                'db_table': 'deleted_employees',
            },
        ),
        migrations.CreateModel(
            name='DeletedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company_logoes/')),
                ('field', models.CharField(choices=[('it', 'Information Technologies'), ('ecommerce', 'E-Commerce'), ('marketing_sales', 'Marketing & Sales')], max_length=500)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.BigIntegerField(blank=True, null=True)),
                ('longitude', models.BigIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=500)),
                ('info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('ceo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'deleted_companies',
            },
        ),
        migrations.CreateModel(
            name='DeletedClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_employees', to='users.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_clients', to='users.user')),
            ],
            options={
                'db_table': 'deleted_clients',
            },
        ),
    ]
