# Generated by Django 4.2.1 on 2023-06-16 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_company_update_at_employee_update_at_and_more'),
        ('users', '0001_initial'),
        ('deleteds', '0001_initial'),
        ('mediafiles', '0002_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduserbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='deletedteambadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediafiles.badge'),
        ),
        migrations.AddField(
            model_name='deletedteambadge',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.team'),
        ),
        migrations.AddField(
            model_name='deletedteam',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='deletedsubscriptionplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='deletedsavedproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project'),
        ),
        migrations.AddField(
            model_name='deletedsavedproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='deletedrankingproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project'),
        ),
        migrations.AddField(
            model_name='deletedrankingproject',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='deletedproject',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='deletedpost',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AddField(
            model_name='deletedmember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.team'),
        ),
        migrations.AddField(
            model_name='deletedmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='deletedemployee',
            name='company',
            field=models.ManyToManyField(to='company.company'),
        ),
        migrations.AddField(
            model_name='deletedemployee',
            name='user',
            field=models.ManyToManyField(to='users.user'),
        ),
        migrations.AddField(
            model_name='deletedcompany',
            name='ceo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
        migrations.AddField(
            model_name='deletedclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_employees', to='users.user'),
        ),
        migrations.AddField(
            model_name='deletedclient',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_clients', to='users.user'),
        ),
    ]
